name: notebook
channels:
- conda-forge
- defaults
dependencies:
- pymc3=3.2=py36_0
- python=3.6.1=2
- ipykernel=4.6.1=py36_0
- ipython=6.2.1=py36_0
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.0.1=py_2
- jsonschema=2.6.0=py36_0
- jupyter=1.0.0=py36_0
- jupyter_client=5.1.0=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_contrib_core=0.3.3=py36_0
- jupyter_contrib_nbextensions=0.3.2=py36_0
- jupyter_core=4.3.0=py36_0
- jupyter_highlight_selected_word=0.0.11=py36_0
- jupyter_latex_envs=1.3.8.2=py36_1
- jupyter_nbextensions_configurator=0.2.8=py36_0
- matplotlib=2.0.2=py36_2
- seaborn
